InmobiliariaConstante/Models/Contrato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace InmobiliariaConstante.Models
{
    public class Contrato
    {
        [Display(Name = "Código")]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Inquilino")]
        public int IdInquilino { get; set; }
        [ForeignKey(nameof(IdInquilino))]
        public Inquilino inquilino { get; set; }
        [Required]
        [Display(Name = "Inmueble")]
        public int IdInmueble { get; set; }
        [ForeignKey(nameof(IdInmueble))]
        public Inmueble inmueble { get; set; }
        [Required]
        [Display(Name = "Garante")]
        public int IdGarante { get; set; }
        [ForeignKey(nameof(IdGarante))]
        public Garante garante { get; set; }
        [Required]
        public DateTime FechaDesde { get; set; }
        [Required]
        public DateTime FechaHasta { get; set; }
        [Display(Name = "Cuotas Contrato")]
        [Required]
        public int Cuotas { get; set; }
        public bool Estado { get; set; }
    }
}

InmobiliariaConstante/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InmobiliariaConstante.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace InmobiliariaConstante.Controllers
{
    [Authorize]
    public class ContratoController : Controller
    {
        private readonly IRepositorioInquilino repoInquilino;
        private readonly IRepositorioInmueble repoInmueble;
        private readonly IRepositorioContrato repoContrato;
        private readonly IRepositorioGarante repoGarante;
        private readonly IRepositorioPago repoPago;
        private readonly IConfiguration config;

        public ContratoController(IConfiguration config, IRepositorioPago repoPago,IRepositorioInquilino repoInquilino, IRepositorioInmueble repoInmueble, IRepositorioContrato repoContrato, IRepositorioGarante repoGarante)
        {
            this.repoInquilino = repoInquilino;
            this.repoInmueble = repoInmueble;
            this.repoContrato = repoContrato;
            this.repoGarante = repoGarante;
            this.repoPago = repoPago;
            this.config = config;
        }

        // GET: ContratoController
        public ActionResult Index(string malo)
        {
            var inquilino = TempData["Inquilino"];
            var cuotas = TempData["Cuotas"];
            if (inquilino != null)
            {
                ViewBag.Cuotas = cuotas;
                ViewBag.Inquilino = inquilino;
            }
            ViewBag.Malo = malo;
            var lista = repoContrato.ObtenerTodos();
            return View(lista);
        }

        // GET: ContratoController/Details/5
        public ActionResult Details(int id)
        {
            var entidad = repoContrato.ObtenerPorId(id);
            return View(entidad);
        }

        // GET: ContratoController/Create
        public ActionResult Create()
        {
            ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
            ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
            ViewBag.Garantes = repoGarante.ObtenerTodos();
            return View();
        }

        // POST: ContratoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contrato entidad)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    entidad.Estado = true;
                    repoContrato.Alta(entidad);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
                    ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
                    ViewBag.Garantes = repoGarante.ObtenerTodos();
                    return View(entidad);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
                ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
                ViewBag.Garantes = repoGarante.ObtenerTodos();
                return View(entidad);
            }
        }

        // GET: ContratoController/Edit/5
        public ActionResult Edit(int id)
        {
            var entidad = repoContrato.ObtenerPorId(id);
            ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
            ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
            ViewBag.Garantes = repoGarante.ObtenerTodos();
            return View(entidad);
        }

        // POST: ContratoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Contrato entidad)
        {
            try
            {
                entidad.Id = id;
                repoContrato.Modificacion(entidad);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
                ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
                ViewBag.Garantes = repoGarante.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: ContratoController/Delete/5
        public ActionResult Delete(int id)
        {
            var entidad = repoContrato.ObtenerPorId(id);
            return View(entidad);
        }

        // POST: ContratoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Contrato entidad) {       
            try
            {
                var contrato = repoContrato.ObtenerPorId(id);
                DateTime fechaDesde = contrato.FechaDesde;
                DateTime fechaHasta = contrato.FechaHasta;
                var hoy = DateTime.Now;
                var diferenciaHoras = (fechaHasta - fechaDesde).TotalHours;
                var mitad = diferenciaHoras / 2;
                var diferenciaToDay = (hoy - fechaDesde).TotalHours;
                if (mitad > diferenciaToDay)
                {
                    TempData["Cuotas"] = "Contrato finalizado, debe 2 Meses de alquiler";
                    TempData["Inquilino"] = contrato.inquilino.Nombre + " " + contrato.inquilino.Apellido;
                }
                else
                {
                    TempData["Cuotas"] = "Contrato finalizado, debe 1 mes de alquiler";
                    TempData["Inquilino"] = contrato.inquilino.Nombre + " " + contrato.inquilino.Apellido;
                }
                contrato.FechaHasta = hoy;
                repoContrato.Modificacion(contrato);
                repoContrato.Baja(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        //POST: Inmuebles/Buscar/5
        [Route("[controller]/Buscar/{fechaDesde}/{FechaHasta}/{idActual}", Name = "Buscar")]
        public IActionResult Buscar(DateTime fechaDesde, DateTime fechaHasta, int idActual)
        {
            try
            {

                    var res = repoContrato.obtenerInmuebles(fechaDesde,fechaHasta,idActual);
                return Json(new { Datos = res });
            }
            catch (Exception ex)
            {
                return Json(new { Error = ex.Message });
            }
        }
    }
}

InmobiliariaConstante/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InmobiliariaConstante.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace InmobiliariaConstante.Controllers
{
    [Authorize]
    public class PagoController : Controller
    {
        private readonly IRepositorioContrato repoContrato;
        private readonly IRepositorioPago repoPago;
        private readonly IConfiguration config;
        public PagoController(IConfiguration config, IRepositorioContrato repoContrato, IRepositorioPago repoPago)
        {
            this.repoContrato = repoContrato;
            this.repoPago = repoPago;
            this.config = config;
        }

        // GET: PagoController
        public ActionResult Index(int id)
        {
            var entidad = repoPago.ObtenerTodos(id);
            var total = repoPago.ObtenerTotal(id);
            var contrato = repoContrato.ObtenerPorId(id);
            var valorInmueble = contrato.inmueble.Precio;
            var cuotas = contrato.Cuotas;
            if (total >= valorInmueble)
            {
              ViewBag.Mensaje = "Este Contrato ha finalizado";
            }
            ViewBag.Id = id;
            ViewBag.ValorInmueble = valorInmueble;
            ViewBag.Cuotas = cuotas;
            ViewBag.Inquilino = contrato.inquilino.Nombre + " " + contrato.inquilino.Apellido;
            
            return View(entidad);
        }

        public ActionResult Delete(int id)
        {
            var entidad = repoPago.ObtenerPorId(id);
            return View(entidad);
        }

        // POST: UsuariosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                repoPago.Baja(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PagoController/Details/5
        public ActionResult Details(int id)
        {
            var entidad = repoPago.ObtenerPorId(id);
            ViewBag.IdContrato = entidad.IdContrato;
            ViewBag.Id = entidad.Id;
            return View(entidad);
        }

        // GET: PagoController/Create
        public ActionResult Create(int id, decimal valorInmueble, int cuotas)
        {
            var total = repoPago.ObtenerTotal(id);
            var valor = valorInmueble / cuotas;
            var diferencia = valorInmueble - total;
            if(diferencia < valor)
            {
                ViewBag.MontoSugerido = diferencia;
            }
            else
            {
                ViewBag.MontoSugerido = valor;
            }
                ViewBag.MontoRestante = diferencia;
            ViewBag.Id = id;
            return View();
        }

        // POST: PagoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pago pago)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = pago.IdContrato;
                    var contrato = repoContrato.ObtenerPorId(id);
                    var entidad = repoPago.ObtenerTotal(id);
                    if (entidad > 0)
                    {
                        var diferencia = contrato.inmueble.Precio - entidad;
                        if (pago.Monto > diferencia)
                        {
                            ModelState.AddModelError("", "El valor supera al monto restante de pago");
                            return View();
                        }
                    }
                    Random r = new Random();
                    var hoy = DateTime.Now;
                    var numero = 0;
                    do
                    {
                        numero = r.Next(1, 1000);
                    } while (repoPago.ObtenerPorNumeroPago(numero) != null);
                    pago.FechaDePago = hoy;
                    pago.NumeroDePago = numero;
                    repoPago.Alta(pago);
                    return RedirectToAction("index", new { id });
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return View(pago);
            }
        }

        public ActionResult Edit(int id)
        {
            var pago = repoPago.ObtenerPorId(id);
            var entidad = repoContrato.ObtenerPorId(pago.IdContrato);
            var total = repoPago.ObtenerTotal(pago.IdContrato);
            var valorInmueble = entidad.inmueble.Precio;
            var cuotas = entidad.Cuotas;
            var valor = valorInmueble / cuotas;
            var diferencia = valorInmueble - total;
            if (diferencia < valor)
            {
                ViewBag.MontoSugerido = diferencia;
            }
            else
            {
                ViewBag.MontoSugerido = valor;
            }
            ViewBag.MontoRestante = diferencia;
            ViewBag.Id = entidad.Id;
            return View(pago);
        }

        // POST: ContratoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Pago pago)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int id = pago.IdContrato;
                    var contrato = repoContrato.ObtenerPorId(id);
                    var entidad = repoPago.ObtenerTotal(id);
                    var pagoViejo = repoPago.ObtenerPorId(pago.Id);
                    if (entidad > 0)
                    {
                        var diferencia = contrato.inmueble.Precio - entidad;
                        if (pago.Monto > diferencia)
                        {
                            ModelState.AddModelError("", "El valor supera al monto restante de pago");
                            return View();
                        }
                    }
                    pago.NumeroDePago = pagoViejo.NumeroDePago;
                    pago.FechaDePago = pagoViejo.FechaDePago;
                    repoPago.Modificacion(pago);
                    return RedirectToAction("Index", new { id = id });
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return View(pago);
            }
        }
    }
}

InmobiliariaConstante/Views/Contrato/Create.cshtml
@model InmobiliariaConstante.Models.Contrato

@{
    ViewData["Title"] = "Crear Contrato";
    var Garantes = (IList<Garante>)ViewBag.Garantes;
    var Inmuebles = (IList<Inmueble>)ViewBag.Inmuebles;
    var Inquilinos = (IList<Inquilino>)ViewBag.Inquilinos;
}

<h1>Crear nuevo Contrato</h1>

<h4>Contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Inquilino: </label>
                <select class="form-control" name="IdInquilino" asp-for="IdInquilino" >
                    @foreach (Inquilino val in Inquilinos)
                    {
                        @:<option value="@val.IdInquilino">@(val.Nombre +" "+ val.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="IdInquilino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDesde" class="control-label"></label>
                <input asp-for="FechaDesde" id="selectDesde" class="form-control" type="date" />
                <span asp-validation-for="FechaDesde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaHasta" class="control-label"></label>
                <input asp-for="FechaHasta" id="selectHasta" class="form-control" type="date" />
                <span asp-validation-for="FechaHasta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Inmueble: </label>
                <select asp-for="IdInmueble" class="form-control" id="selectInmueble" name="IdInmueble">
                    <option selected value="Seleccione un Inmueble">-- Seleccione un Inmueble --</option>
                </select>
                <span asp-validation-for="IdInmueble" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuotas" class="control-label"></label>
                <input asp-for="Cuotas" class="form-control" />
                <span asp-validation-for="Cuotas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Garante: </label>
                <select asp-for="IdGarante"  class="form-control" name="IdGarante">
                    @foreach (Garante val in Garantes)
                    {
                        @:<option  value="@val.Id">@(val.Nombre +" "+ val.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="IdGarante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>
<script type="text/javascript">
    var selectDesde = document.getElementById('selectDesde');
    var selectHasta = document.getElementById('selectHasta');
    var selectInmueble = document.getElementById('selectInmueble');
    function buscarInmueblesSelect() {
        let myObjectJSON = {};
        var FechaDesde = selectDesde.value;
        var FechaHasta = selectHasta.value;
        url = `@Url.Action("Buscar", "Contrato", new { fechaDesde = "fechaDesde", fechaHasta = "fechaHasta" , idActual = "idActual"})`;
        url = url.replace("fechaDesde", FechaDesde)
            .replace("fechaHasta", FechaHasta)
            .replace("idActual",null);
        return $.ajax({
            url: url,
        }).done(res => {
            myObjectJSON = res;
            if (!myObjectJSON.datos) {
                return;
            }
            selectInmueble.innerHTML = "";
            for (let x of myObjectJSON.datos) {
                let option = document.createElement("option");
                option.value = x.id;
                option.text = x.direccion+" $"+x.precio;
                selectInmueble.add(option);
            }
        }).fail(res => {
            console.log("Error: ", res);
        });
    }

    function obtener() {
        const $select = document.querySelector("#selectInmueble");
        var FechaDesde = selectDesde.value;
        var FechaHasta = selectHasta.value;
        if ((FechaDesde.length != 0) && (FechaHasta.length != 0)) {
            if (FechaDesde < FechaHasta) {
                buscarInmueblesSelect();
            } else {
                for (let i = $select.options.length; i >= 0; i--) {
                    $select.remove(i);
                }
                const option = document.createElement('option');
                option.text = "-- Seleccione fechas correctas --";
                $select.appendChild(option);
                alert("La Fecha de inicio debe ser menor a la final")
                return false;
            }
        }
    }

    selectHasta.addEventListener('change', () => {
        obtener();
    });
    selectDesde.addEventListener('change', () => {
        obtener();
    })


</script>

InmobiliariaConstante/Views/Contrato/Edit.cshtml
@model InmobiliariaConstante.Models.Contrato

@{
    ViewData["Title"] = "Edit";
    var Garantes = (IList<Garante>)ViewBag.Garantes;
    var Inmuebles = (IList<Inmueble>)ViewBag.Inmuebles;
    var Inquilinos = (IList<Inquilino>)ViewBag.Inquilinos;
}

<h1>Editar</h1>

<h4>Contrato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" id="idActual" value="@(Model.IdInmueble)"/>
            <div class="form-group">
                <label class="control-label">Inquilino: </label>
                <select class="form-control" name="IdInquilino" asp-for="IdInquilino">
                    @foreach (Inquilino val in Inquilinos)
                    {
                        @:<option @(val.IdInquilino == Model.IdInquilino ? "selected" : "") value="@val.IdInquilino">@(val.Nombre +" "+ val.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="IdInquilino" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDesde" class="control-label"></label>
                <input asp-for="FechaDesde" id="selectDesde" class="form-control" type="date" />
                <span asp-validation-for="FechaDesde" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaHasta" class="control-label"></label>
                <input asp-for="FechaHasta" id="selectHasta" class="form-control" type="date" />
                <span asp-validation-for="FechaHasta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Inmueble: </label>
                <select class="form-control" id="selectInmueble" name="IdInmueble" asp-for="IdInmueble">
                    @foreach (Inmueble val in Inmuebles)
                    {
                        @:<option @(val.Id == Model.Id ? "selected" : "") value="@val.Id">@(val.Direccion +" $"+ val.Precio)</option>
                    }
                </select>
                <span asp-validation-for="IdInmueble" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuotas" class="control-label"></label>
                <input asp-for="Cuotas" class="form-control" />
                <span asp-validation-for="Cuotas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Garante: </label>
                <select class="form-control" name="IdGarante" asp-for="IdGarante">
                    @foreach (Garante val in Garantes)
                    {
                        @:<option @(val.Id == Model.IdGarante ? "selected" : "") value="@val.Id">@(val.Nombre +" "+ val.Apellido)</option>
                    }
                </select>
                <span asp-validation-for="IdGarante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>
<script type="text/javascript">
    debugger;
    var selectDesde = document.getElementById('selectDesde');
    var selectHasta = document.getElementById('selectHasta');
    var selectInmueble = document.getElementById('selectInmueble');
    var id = document.getElementById('idActual');
    function buscarInmuebles() {
        let myObjectJSON = {};
        var FechaDesde = selectDesde.value;
        var FechaHasta = selectHasta.value;
        var IdActual = id.value;
        url = `@Url.Action("Buscar", "Contrato", new { fechaDesde = "fechaDesde", fechaHasta = "fechaHasta", idActual = "idActual" })`;
        url = url.replace("fechaDesde", FechaDesde)
            .replace("fechaHasta", FechaHasta)
            .replace("idActual", IdActual);
        return $.ajax({
            url: url,
        }).done(res => {
            myObjectJSON = res;
            if (!myObjectJSON.datos) {
                return;
            }
            selectInmueble.innerHTML = "";
            for (let x of myObjectJSON.datos) {
                let option = document.createElement("option");
                option.value = x.id;
                option.text = x.direccion +" $"+x.precio;
                selectInmueble.add(option);
            }
        }).fail(res => {
            console.log("Error: ", res);
        });
    }


    selectHasta.addEventListener('change', () => {
        const $select = document.querySelector("#selectInmueble");
        var FechaDesde = selectDesde.value;
        var FechaHasta = selectHasta.value;
        if (FechaDesde < FechaHasta) {
            buscarInmuebles();
        } else {
            for (let i = $select.options.length; i >= 0; i--) {
                $select.remove(i);
            }
            const option = document.createElement('option');
            option.text = "-- Seleccione fechas correctas --";
            $select.appendChild(option);
            alert("La Fecha de inicio debe ser menor a la final")
            return false;
        }
    });

</script>

InmobiliariaConstante/Views/Contrato/Index.cshtml
@model IEnumerable<InmobiliariaConstante.Models.Contrato>

@{
    ViewData["Title"] = "Contratos";
    var malo = ViewBag.Malo;
}

<h1>Contratos</h1>

@{ if (ViewBag.Cuotas != null)
    {//Cancelar Contrato
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>¡EnHorabuena @ViewBag.Inquilino!</strong> @ViewBag.Cuotas
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><span class="lnr lnr-cross-circle"></span></span>
            </button>
        </div>
    }
}
<p>
    <a asp-action="Create">Crear nuevo Contrato</a>
</p>
<p>
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#asd" aria-expanded="false" aria-controls="collapseExample">
        Ver Inmuebles disponibles
    </button>
</p>
<div class="collapse" id="asd">
    <div class="card card-body">
        <div class="form-row">
            <label class="control-label">Fecha Inicio</label>
            <input id="fechaInicio" class="form-control" type="date" />
            <label class="control-label">Fecha de cierre</label>
            <input id="fechaFinal" class="form-control" type="date" />
            @{if (malo != null)
            {
                        <span class="text-danger" id="mensajeFecha">@malo</span>
            } 

            }
            
        </div>
        <a class="btn btn-primary" data-toggle="modal" href="#exampleModal" onclick="buscarInmueblesDisponibles()">
            Buscar
        </a>
    </div>
</div>
<table class="table" id="mi-tabla">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdInquilino)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.inmueble.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuotas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdGarante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDesde)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaHasta)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @(item.inquilino.Nombre + " " + item.inquilino.Apellido)
                </td>
                <td>
                    @(item.inmueble.Direccion)
                </td>
                <td>
                    @(item.Cuotas)
                </td>
                <td>
                    @(item.garante.Nombre + " " + item.garante.Apellido)
                </td>
                @{ if (item.Estado == false)
                    {
                        <td>
                            Contrato Cancelado
                        </td>
                    }
                    else
                    {
                        <td>
                            Contrato Vigente
                        </td>
                    }
                }
                <td>
                    @(item.FechaDesde.ToString("d"))
                </td>
                <td>
                    @(item.FechaHasta.ToString("d"))
                </td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a asp-controller="Contrato" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary" title="Detalles"><i class="fas fa-info"></i></a>
                        @{ if (item.Estado != false)
                            {
                                <a asp-controller="Contrato" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary" title="Editar"><i class="fas fa-user-edit"></i></a>
                                <a asp-controller="Contrato" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger" title="Eliminar"><i class="fas fa-user-minus"></i></a>
                                <a asp-controller="Pago" asp-action="Index" asp-route-id="@item.Id" class="btn btn-success" title="Pagos"><i class="fas fa-hand-holding-usd"></i></a>
                            }
                        }

                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>