InmobiliariaConstante/Models/LoginView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InmobiliariaConstante.Models
{
    public class LoginView
    {
        [DataType(DataType.EmailAddress)]
        public string Usuario { get; set; }
        [DataType(DataType.Password)]
        public string Clave { get; set; }
    }
}

InmobiliariaConstante/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InmobiliariaConstante.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace InmobiliariaConstante.Controllers
{
    [Authorize]
    public class ContratoController : Controller
    {
        private readonly IRepositorioInquilino repoInquilino;
        private readonly IRepositorioInmueble repoInmueble;
        private readonly IRepositorioContrato repoContrato;
        private readonly IRepositorioGarante repoGarante;
        private readonly IRepositorioPago repoPago;
        private readonly IConfiguration config;

        public ContratoController(IConfiguration config, IRepositorioPago repoPago,IRepositorioInquilino repoInquilino, IRepositorioInmueble repoInmueble, IRepositorioContrato repoContrato, IRepositorioGarante repoGarante)
        {
            this.repoInquilino = repoInquilino;
            this.repoInmueble = repoInmueble;
            this.repoContrato = repoContrato;
            this.repoGarante = repoGarante;
            this.repoPago = repoPago;
            this.config = config;
        }

        // GET: ContratoController
        public ActionResult Index(string malo)
        {
            var inquilino = TempData["Inquilino"];
            var cuotas = TempData["Cuotas"];
            if (inquilino != null)
            {
                ViewBag.Cuotas = cuotas;
                ViewBag.Inquilino = inquilino;
            }
            ViewBag.Malo = malo;
            var lista = repoContrato.ObtenerTodos();
            return View(lista);
        }

        // GET: ContratoController/Details/5
        public ActionResult Details(int id)
        {
            var entidad = repoContrato.ObtenerPorId(id);
            return View(entidad);
        }

        // GET: ContratoController/Create
        public ActionResult Create()
        {
            ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
            ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
            ViewBag.Garantes = repoGarante.ObtenerTodos();
            return View();
        }

        // POST: ContratoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contrato entidad)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    entidad.Estado = true;
                    repoContrato.Alta(entidad);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
                    ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
                    ViewBag.Garantes = repoGarante.ObtenerTodos();
                    return View(entidad);
                }
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
                ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
                ViewBag.Garantes = repoGarante.ObtenerTodos();
                return View(entidad);
            }
        }

        // GET: ContratoController/Edit/5
        public ActionResult Edit(int id)
        {
            var entidad = repoContrato.ObtenerPorId(id);
            ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
            ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
            ViewBag.Garantes = repoGarante.ObtenerTodos();
            return View(entidad);
        }

        // POST: ContratoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Contrato entidad)
        {
            try
            {
                entidad.Id = id;
                repoContrato.Modificacion(entidad);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Inmuebles = repoInmueble.ObtenerTodos();
                ViewBag.Inquilinos = repoInquilino.ObtenerTodos();
                ViewBag.Garantes = repoGarante.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: ContratoController/Delete/5
        public ActionResult Delete(int id)
        {
            var entidad = repoContrato.ObtenerPorId(id);
            return View(entidad);
        }

        // POST: ContratoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Contrato entidad) {       
            try
            {
                var contrato = repoContrato.ObtenerPorId(id);
                DateTime fechaDesde = contrato.FechaDesde;
                DateTime fechaHasta = contrato.FechaHasta;
                var hoy = DateTime.Now;
                var diferenciaHoras = (fechaHasta - fechaDesde).TotalHours;
                var mitad = diferenciaHoras / 2;
                var diferenciaToDay = (hoy - fechaDesde).TotalHours;
                if (mitad > diferenciaToDay)
                {
                    TempData["Cuotas"] = "Contrato finalizado, debe 2 Meses de alquiler";
                    TempData["Inquilino"] = contrato.inquilino.Nombre + " " + contrato.inquilino.Apellido;
                }
                else
                {
                    TempData["Cuotas"] = "Contrato finalizado, debe 1 mes de alquiler";
                    TempData["Inquilino"] = contrato.inquilino.Nombre + " " + contrato.inquilino.Apellido;
                }
                contrato.FechaHasta = hoy;
                repoContrato.Modificacion(contrato);
                repoContrato.Baja(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        //POST: Inmuebles/Buscar/5
        [Route("[controller]/Buscar/{fechaDesde}/{FechaHasta}/{idActual}", Name = "Buscar")]
        public IActionResult Buscar(DateTime fechaDesde, DateTime fechaHasta, int idActual)
        {
            try
            {

                    var res = repoContrato.obtenerInmuebles(fechaDesde,fechaHasta,idActual);
                return Json(new { Datos = res });
            }
            catch (Exception ex)
            {
                return Json(new { Error = ex.Message });
            }
        }
    }
}

InmobiliariaConstante/Controllers/GaranteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InmobiliariaConstante.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace InmobiliariaConstante.Controllers
{
    [Authorize]
    public class GaranteController : Controller
    {
        private readonly IRepositorioGarante repositorio;
        private readonly IConfiguration config;

        public GaranteController(IConfiguration config, IRepositorioGarante repositorio)
        {
            this.repositorio = repositorio;
            this.config = config;
        }

        // GET: Inquilino
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerTodos();
            return View(lista);
        }

        // GET: Inquilino/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var entidad = repositorio.ObtenerPorId(id);
                return View(entidad);
            }
            catch (Exception ex)
            {//poner breakpoints para detectar errores
                throw;
            }
        }

        // GET: Inquilino/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Inquilino/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Garante propietario)
        {
            try
            {
                TempData["Nombre"] = propietario.Nombre;
                repositorio.Alta(propietario);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Inquilino/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                var entidad = repositorio.ObtenerPorId(id);
                return View(entidad);
            }
            catch (Exception ex)
            {
                throw;
            }

        }

        // POST: Inquilino/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Garante i)
        {
            Garante garante = null;
            try
            {
                garante = repositorio.ObtenerPorId(id);
                garante.Nombre = i.Nombre;
                garante.Apellido = i.Apellido;
                garante.Dni = i.Dni;
                garante.Email = i.Email;
                garante.Telefono = i.Telefono;
                repositorio.Modificacion(garante);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Inquilino/Delete/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Delete(int id)
        {
            Garante garante = repositorio.ObtenerPorId(id);
            return View(garante);
        }

        // POST: Inquilino/Delete/5
        [Authorize(Policy = "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                repositorio.Baja(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

InmobiliariaConstante/Controllers/InmueblesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InmobiliariaConstante.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace InmobiliariaConstante.Controllers
{
    [Authorize]
    public class InmueblesController : Controller
    {
        private readonly IRepositorioInmueble repositorio;
        private readonly IRepositorioPropietario repoPropietario;
        private readonly IConfiguration config;

        public InmueblesController(IConfiguration config, IRepositorioInmueble repositorio, IRepositorioPropietario repoPropietario)
        {
            this.repositorio= repositorio;
            this.repoPropietario = repoPropietario;
            this.config = config;
        }

        // GET: Inmueble
        public ActionResult Index()
        {
            var lista = repositorio.ObtenerTodos();
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            return View(lista);
        }

        public ActionResult PorPropietario(int id)
        {
            var lista = repositorio.BuscarPorPropietario(id);
            if (TempData.ContainsKey("Id"))
                ViewBag.Id = TempData["Id"];
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            ViewBag.Id = id;
            //ViewBag.Propietario = repoPropietario.
            return View("Index", lista);
        }

        // GET: Inmueble/Details/5
        public ActionResult Details(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            return View(entidad);
        }

        // GET: Inmueble/Create
        public ActionResult Create()
        {
            
            IList<Propietario> res = repoPropietario.ObtenerTodos();
            ViewData["Propietarios"] = res;
            return View();
        }

        // POST: Inmueble/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Inmueble entidad)
        {
            try
            {
                entidad.Estado = true;
                repositorio.Alta(entidad);
                TempData["Id"] = entidad.Id;
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ViewBag.Propietarios = repoPropietario.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: Inmueble/Edit/5
        public ActionResult Edit(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            ViewBag.Propietarios = repoPropietario.ObtenerTodos();
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(entidad);
        }

        // POST: Inmueble/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Inmueble entidad)
        {
            try
            {
                entidad.Id = id;
                repositorio.Modificacion(entidad);
                TempData["Mensaje"] = "Datos guardados correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Propietarios = repoPropietario.ObtenerTodos();
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        // GET: Inmueble/Eliminar/5
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id)
        {
            var entidad = repositorio.ObtenerPorId(id);
            if (TempData.ContainsKey("Mensaje"))
                ViewBag.Mensaje = TempData["Mensaje"];
            if (TempData.ContainsKey("Error"))
                ViewBag.Error = TempData["Error"];
            return View(entidad);
        }

        // POST: Inmueble/Eliminar/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "Administrador")]
        public ActionResult Eliminar(int id, Inmueble entidad)
        {
            try
            {
                repositorio.Baja(id);
                TempData["Mensaje"] = "Eliminación realizada correctamente";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewBag.StackTrate = ex.StackTrace;
                return View(entidad);
            }
        }

        [Route("[controller]/BuscarInmuebles/{id}", Name = "BuscarInmuebles")]
        public IActionResult BuscarInmuebles(int id)
        {
            try
            {
                var res = repoPropietario.ObtenerInmueblesXPropietario(id);
                return Json(new { Datos = res });
            }
            catch (Exception ex)
            {
                return Json(new { Error = ex.Message });
            }
        }

        [Route("[controller]/InmueblesXContrato/{id}", Name = "InmueblesXContrato")]
        public IActionResult InmueblesXContrato(int id)
        {
            try
            {
                var res = repositorio.ObtenerInmueblesXContrato(id);
                return Json(new { Datos = res });
            }
            catch (Exception ex)
            {
                return Json(new { Error = ex.Message });
            }
        }
    }
}

InmobiliariaConstante/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InmobiliariaConstante</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/b5594b9b95.js" crossorigin="anonymous"></script>
    <link rel="icon" href="~/img/favicon.png" type="image/x-icon" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3" >
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inmobiliaria Constante</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="color:white;">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Propietarios" asp-action="Index">Propietarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Inquilinos" asp-action="Index">Inquilinos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Inmuebles" asp-action="Index">Inmuebles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Garante" asp-action="Index">Garantes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Contrato" asp-action="Index">Contratos</a>
                            </li>
                        }
                    </ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class="dropdown">
                            <a class="btn btn-primary dropdown-toggle text-light" href="#" role="button" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-reference="parent" data-display="static">
                                <span class="lnr lnr-user"></span> @User.Identity.Name
                            </a>

                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item text-dark" asp-controller="Usuarios" asp-action="Perfil"><i class="lnr lnr-user"></i> Perfil</a>
                                <a class="dropdown-item text-dark" asp-controller="Usuarios" asp-action="Logout"><i class="lnr lnr-exit"></i> Salir</a>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <!-- Modal -->
            <div class="modal fade bd-example-modal-xl" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true" >
                <div class="modal-dialog modal-xl" role="document">
                    <div class="modal-content">
                        <div class="modal-header" style="background-color:black;color:white;">
                            <h5 class="modal-title" id="titulo"></h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" >
                            <table class="table">
                                <thead style="background-color:black;color:white;">
                                    <tr>
                                        <th>
                                            Codigo
                                        </th>
                                        <th>
                                            Direccion
                                        </th>
                                        <th>
                                            Ambientes
                                        </th>
                                        <th>
                                            Superficie
                                        </th>
                                        <th>
                                            Latitud
                                        </th>
                                        <th>
                                            Longitud
                                        </th>
                                        <th>
                                            Estado
                                        </th>
                                        <th>
                                            Precio
                                        </th>
                                        <th>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody id="tbodypa" style="font-weight: bold; background: rgb(2,0,36); background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(0,212,255,1) 0%, rgba(177,110,38,1) 0%, rgba(217,150,45,1) 0%, rgba(154,126,64,1) 65%, rgba(126,115,72,1) 99%);">
                                </tbody>
                            </table>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal -->
            <!-- Modal Inmuebles X Contrato -->
            <div class="modal fade bd-example-modal-xl" id="inmueblesXContrato" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-xl" role="document">
                    <div class="modal-content">
                        <div class="modal-header" style="background-color:black;font-weight:bold; color:white;">
                            <h5 class="modal-title" id="tcontrato"></h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body" style="background: rgb(2,0,36); background: linear-gradient(90deg, rgba(2,0,36,1) 0%, rgba(0,212,255,1) 0%, rgba(177,110,38,1) 0%, rgba(72,118,126,1) 90%);">
                            <table class="table">
                                <thead style="background-color:black;color:white;">
                                    <tr>
                                        <th>
                                            Codigo
                                        </th>
                                        <th>
                                            Inquilino
                                        </th>
                                        <th>
                                            Cuotas
                                        </th>
                                        <th>
                                            Estado
                                        </th>
                                        <th>
                                            Fecha de Inicio
                                        </th>
                                        <th>
                                            Fecha de fin
                                        </th>
                                    </tr>
                                </thead>
                                <tbody id="tbodycontratos" style="font-weight:bold;">
                                </tbody>
                            </table>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal Inmuebles X Contrato -->
        </main>
    </div>
    @RenderSection("Scripts", false)
    @await Html.PartialAsync("_ValidationScriptsPartial")
</body>
</html>

InmobiliariaConstante/Views/Shared/_Login.cshtml
@model InmobiliariaConstante.Models.LoginView

<h4>Acceso</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Usuarios" asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Usuario" class="control-label"></label>
                <input asp-for="Usuario" class="form-control" />
                <span asp-validation-for="Usuario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clave" class="control-label"></label>
                <input asp-for="Clave" class="form-control" />
                <span asp-validation-for="Clave" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Entrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>